apiVersion: v1
kind: Service
metadata:
  name: todolist
  labels:
    app: todolist
spec:
  selector:
    app: todolist
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30000
  type: LoadBalancer